language: node_js
cache: yarn
node_js:
- node
script: yarn start & yarn test && yarn lint
deploy:
  provider: npm
  email: npm@netflix.com
  on:
    tags: true
  api_key:
    secure: i/rxJfLgLKQahqGjTSKE5SMFlXDd/ah+eTbpNKDpUx6tvNtDvz1kKLALSX2sUsHDHmpqDiegO7x8hiLc1m6TTnNforSbvrRcl9DJwytqeIFuKm/xXsF5CduFVTUxMtzHg0xLbJKDiv+W3vNf+eObpbpfCJ3JYKWyuwWbvffJz3wcaZI9m4zR0ZRNh/aB+CHkh5PktgbXG4pJM+Y7wcGJtZKcDyGFZSrthZCtjXDpn7ANp3OB8ZyBlJmS0OfpgpdHYDJ3/yTf9Acrnk7Fvrr4VidO7Pqc4g/4FFjOuRCgC9pDbJ5vszNOXiBcY0FwGE5hC79HjbdwmnIIyGyQkKjQdFAGUt2dGfuTIvmAoArTzq8GAtS/Q82se4ePiIPEf4dv5ZThx2dfTFrVEhQCLWRwziG5Tt4Ctk7pBc7M0pdv2MkhQyrLBAV3zGqV2LMqZYN5qz3o7TXGmLR9CnOLYUuo7531yJSfPbFfI1KJ4EWltUER8yu0OIa66BG1BrgfHT4WiR6X2FcQZmpjulWflrS86GoFqG+/HY8G0ZZM3NBbbpDS5tK7q6zMKATG9iyD0jv6/MLPPhdyXaTmqa7pHt2zeQsyrndBN7UVfjE8XLScpz/UpfPZzon0hnml7M/iUJJk4+YXnw/JIwBNL1V8w56xaSqFJ/FOYpv11nTo3UlLZWY=
